/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AppConfigSchema {
  id: string;
  title: string;
  slug: string;
  version: string;
  addToDock?: boolean;
  bin: string;
  icon: {
    "24@2x": string;
    "48@2x": string;
    "256@2x": string;
  };
  "sidebar-view"?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9-_]+$".
     */
    [k: string]: {
      sidebarButton: string;
      subTitle: string;
      icon: string;
    };
  };
}
